### ISSUE TITLE
[INCLUDE] Identify FHIR DocumentReferences for Gene Expression Summary files

### ISSUE THREAD

**Issue by RobertJCarroll** [NIH-NCPI/FHIR-CAT-June22#8]
Save JSON containing all DocumentReferences for INCLUDE Gene Expression Summary files into this bucket: https://console.cloud.google.com/storage/browser/fc-be286b9f-3acf-4168-af6e-592df509391d/DocumentReference
gs://fc-be286b9f-3acf-4168-af6e-592df509391d/DocumentReference

**Comment by adeslatt** [comment]
@RobertJCarroll the second `gs://` does not seem to resolve --

**Comment by torstees** [comment]
This query should work to pull the target files, but only in QA until we get the go ahead to push the file data up to PROD

https://include-api-fhir-service-qa.includedcc.org/DocumentReference?type=Gene-Expression,Gene-Expression-Quantifications&category=https://includedcc.org/fhir/code-systems/experimental_strategies|RNA-Seq&location:missing=false

An example of a query to pull the patients associated with a super set of the files from the above query:
https://include-api-fhir-service-qa.includedcc.org/Patient?_has:DocumentReference:subject:type=Gene-Expression,Gene-Expression-Quantifications

**Comment by RobertJCarroll** [comment]
> @RobertJCarroll the second `gs://` does not seem to resolve --

How are you trying to access this? When authenticated, `gsutil ls gs://fc-be286b9f-3acf-4168-af6e-592df509391d/DocumentReference` worked for me.

**Comment by RobertJCarroll** [comment]
> This query should work to pull the target files, but only in QA until we get the go ahead to push the file data up to PROD

Is there a way to pull this in prod now?

**Comment by torstees** [comment]
Finally, the query that will let normal people access the data: 

https://include-api-fhir-service.includedcc.org/DocumentReference?_tag=HTP&category=RNA-Seq&type=Gene-Expression,Gene-Expression-Quantifications&location:missing=false
